config/routes.rb
Rails.application.routes.draw do
  resources :meals, only: [:index]
  resource  :cart, only: [:show] do
    get :checkout
  end
  resources :order_items, only: [:create, :update, :destroy]
  resources :orders, only: [:index, :edit, :create, :update]
  resources :order_forms
  
  root to:  "meals#index"
  
  get       'sessions/create'
  get       '/auth/:provider/callback', to: 'sessions#create'
  delete    '/logout', to: 'sessions#destroy'
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  has_many :order_items
  VALID_EMAIL_REGEX = /\A([A-Z][^\d\W]|[-])/
  validates :name, presence: true, uniqueness: {case_sensitive: false},
  								 format: {with: VALID_EMAIL_REGEX}

  default_scope { where(active: true) }
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many  :order_items
  belongs_to :user

  enum status: [ :Delivered, :Ordered]

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
end

app/models/order_form.rb
class OrderForm
	include ActiveModel::Model

	attr_accessor :user, :order
	attr_writer :cart

	def save
		set_password_for_user

		if valid?
			persist
			true
		else 
			false
		end
	end

	def has_errors?
		user.errors.any?
	end

	private

	def valid?
		user.valid?
	end

	def persist
		user.save
		@order = Order.create! user: user

		build_order_items
	end

	def set_password_for_user
		user.password = Digest::SHA1.hexdigest(user.email + Time.now.to_s)[0..8]
	end

	def build_order_items
		@cart.items.each do |item|
			@order.order_items.create! product_id: item.product_id, quantity: item.quantity
		end
	end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :meal
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :meal_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      meal.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def meal_present
    if meal.nil?
      errors.add(:meal, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    # debugger
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :orders
	validates :name, 				presence: true
	validates :image_url, 	presence: true

	class << self
	  def from_omniauth(auth_hash)
	    user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
	    user.name = auth_hash['info']['name']
	    user.image_url = auth_hash['info']['image']
	    user.save!
	    user
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order
  helper_method :current_user

  private

    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

    def current_order
      if !session[:order_id].nil?
        Order.find(session[:order_id])
      else
        Order.new
      end
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end

  def checkout	 	
 		@order = current_order
 		@order.update_attributes(subtotal: current_order.subtotal, user_id: current_user.id)
 		@user = current_user
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  
  def index
    @meals = Meal.all
    @order_item = current_order.order_items.new
  end
end

app/controllers/order_forms_controller.rb
class OrderFormsController < ApplicationController
	def update
		@user = User.find(params[:id])
		@user.update_attributes(order_params)
		session.delete(:order_id)
		redirect_to root_path
	end

	private

		def order_params
			params.require(:user).permit( :name, :email )
		end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    @order = current_order
    @order_item = @order.order_items.new(order_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end

private
  def order_item_params
    params.require(:order_item).permit(:quantity, :meal_id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  	@orders = current_user.orders.all
  end

  def edit
  	@order = Order.find(params[:id])
    @statuses = Order.statuses
  end

  def create
  end

  def update
  	@order = Order.find(params[:id])
    @statuses = Order.statuses
    if @order.update_attributes(order_params)
      redirect_to orders_path
      flash[:success] = "The delivery status was changing."
    else
      render "edit"
    end
  end
  
	private
  
    def order_params
      params.require(:order).permit(:subtotal, :status)
    end

    # def order_params
    #   params.require(:order).permit(:subtotal, :status,
    #     user: [:name, :email]
    #     )
    # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  
  def create
    begin
    	@user = User.from_omniauth(request.env['omniauth.auth'])
    	session[:user_id] = @user.id
   	  flash[:success] = "Welcome, #{@user.name}!"
  	rescue
   	 flash[:warning] = "There was an error while trying to authenticate you..."
  	end
  	redirect_to root_path
  end

  def destroy
    if current_user
      session.delete(:user_id)
      flash[:success] = 'See you!'
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/order_forms_helper.rb
module OrderFormsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def logged_in?
		!current_user.nil?
	end
end

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= meal.name %></h4>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :meal_id, value: meal.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the meal '#{order_item.meal.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>
    
  </div>
</div>

app/views/carts/_meals_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no meals in your cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', meal: order_item.meal, order_item: order_item, show_total: true %>
  <% end %>
  <p><%= link_to "Sent Order", checkout_cart_path, class: "btn btn-primary" %></p>
<% end %>

app/views/carts/checkout.html.erb
<h1> Checkout </h1>

<%= form_for @user, url: order_form_path(@user) do |f| %>
 <h3>Some of your personal details</h3>
 	<p><%= f.text_field :name, placeholder: "#{current_user.name}", class: "form-control" %></p>
 	<p><%= f.email_field :email, placeholder: "Email", class: "form-control" %></p>  
 	<p><%= f.submit "Send Order", class: "btn btn-primary" %>
<% end %>

app/views/carts/show.html.erb
<% provide(:title, "Meals Cart") %>

<div class="meals-cart">
  <%= render "meals_cart" %>
</div>

app/views/layouts/_cart_text.html.erb
<%= link_to "#{pluralize(current_order.order_items.size, "Meal")} in Order ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-primary" %>

app/views/layouts/_footer.html.erb
<footer>
	<em>Developed by Arkadiusz Bojanowski</em>
</footer>	

app/views/layouts/_header.html.erb
<div class="row">
  <div class="col-xs-2">
    <h1 class="head"><%= link_to "Meals", root_path %></h1>
  </div>
  <div class="col-xs-3 pull-right text-right">
    <% if current_user %>
      <div class="log">
        <span><%= image_tag current_user.image_url, alt: current_user.name %></span>
        <span><%= link_to 'Log Out', logout_path, method: :delete %></span>
      </div>  
    <% else %> 
      <div class="log">      
        <span><%= link_to 'Log in', '/auth/facebook' %></span>
      </div>
    <% end %>     
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Burger Meals</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <% if request.ssl? %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js' %>
  <% else %> 
    <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js' %>
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render partial: 'layouts/header' %>    
    <hr>
    
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>

    <% if logged_in? %>
      <div class="text-right">
        <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
      </div>
    <% end %>
    


    <%= yield %>

    <%= render partial: 'layouts/footer' %> 
  </div>

</body>
</html>

app/views/meals/_meals_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-1">
      <h4><%= meal.id %>.</small></h4>
    </div>
    <div class="col-xs-4">
      <p><%= image_tag meal.image, width: "175"  %></p>
    </div>
    <div class="col-xs-3">
      <h4><%= meal.name %></small></h4>
    </div>
    <div class="col-xs-4">
      
      <% if logged_in? %>
        <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Price: <span style="color: green"><%= number_to_currency meal.price %></span></h4>
          <div class="input-group">
            <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
            <div class="input-group-btn">
              <%= f.hidden_field :meal_id, value: meal.id %>
              <%= f.submit "Add to Cart", class: "btn btn-primary" %>
            </div>
          </div>
        <% end %>
       <% end %> 
    </div>
    
  </div>
</div>

app/views/meals/index.html.erb
<% provide(:title, "Home") %>

<div class="container welcome">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-1">
      <% if current_user %>    
          <h2 = "hello"> Tasty Burgers .. try two diffrent! </h2>
          <span><%= link_to 'or check orders history ', orders_path %></span>
        <% else %> 
          <h2 = "hello"> Hello in Burger Meals </h2>
          <p> If you want order meal </p>      
          <span><%= link_to 'Log in', '/auth/facebook' %></span>
        <% end %> 
    </div>
    <div class="col-xs-2">
      <img src="https://www.dropbox.com/s/26iiveyjoxmorsi/Salat.png?raw=1">
    </div>  
  </div>
</div>

<h3 class="text-center">Meals</h3>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% @meals.each do |meal| %>
      <%= render "meals_row", meal: meal, order_item: @order_item %>
    <% end %>
  </div>
</div>

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
alert("not valid.")
<% else %>
	<% if @order.order_items(:reload).count <= 2 %>
  	$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
  <% else %>
  	<% @order.order_items.last.destroy %>
		alert("You can't add more than two positions.")
	<% end %>  	
<% end %>

app/views/order_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".meals-cart").html("<%= escape_javascript(render 'carts/meals_cart') %>")

app/views/order_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".meals-cart").html("<%= escape_javascript(render 'carts/meals_cart') %>")

app/views/orders/edit.html.erb
<% provide(:title, "Manage Orders") %>

<div class="container">
  <h3>Editing Order No <%= @order.id %></h3>
  <hr />
  <% if @order.errors.any? %>
    <div class="alert alert-danger">
       <h2>
          <%= pluralize(@user.errors.count, "error")%>
              prohibited this user from being saved:  
          </h2>
          <ul>
            <%= @order.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>   
    </div>
  <% end %>

  <%= form_for @order do |f| %>
    <div class="row">
      <div class="col-xs-12 form-group">
        <%= f.label :subtotal, class: "control-label" %>
        <%= f.number_field :subtotal, class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 form-group">
        <%= f.label :status %>
        <%= f.select :status, options_for_select(@statuses.collect { |s| [s[0].humanize, s[0]] }, selected: @order.status), {} , class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 form-group">
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/orders/index.html.erb
<% provide(:title, "Check Orders") %>

<div class="container">
  <h3>Orders</h3>
  <table class="table table-bordered table-striped">
    <tr>
      <th class="orderNumber">Order No</th>
      <th>Total</th>
      <th>Order Status</th>
      <td class="status">&nbsp;</td>
    </tr>
    <% @orders.each do |order| %>
      <tr>
        <td class="orderNumber"><%= order.id %>.</td>
        <td><%= number_to_currency order.subtotal %></td>
        <td><%= order.status %></td>
        <td class="status"><%= link_to "Change delivery status", edit_order_path(order), class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </table>
</div>